"""Add users table

Revision ID: 0dacc823f716
Revises: 7ab138e9d692
Create Date: 2020-12-07 01:06:17.925049

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0dacc823f716"
down_revision = "7ab138e9d692"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=64), nullable=True),
        sa.Column("time_in_channel", sa.Integer(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.Column("cheers", sa.Integer(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.Column("last_message", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "channel"),
        sa.UniqueConstraint("user"),
    )
    op.create_index(op.f("ix_users_channel"), "users", ["channel"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_channel"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
