"""Add order column, remove priority

Revision ID: 0e0348cf8013
Revises: 8527dda7e7d7
Create Date: 2021-09-18 03:56:47.857223

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0e0348cf8013"
down_revision = "8527dda7e7d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trivia_questions", sa.Column("order", sa.Integer(), nullable=True))
    op.drop_column("trivia_questions", "priority")
    op.execute("UPDATE trivia_questions SET `order` = -1;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trivia_questions", sa.Column("priority", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)
    )
    op.drop_column("trivia_questions", "order")
    # ### end Alembic commands ###
