"""Add viewers column to RaidLog

Revision ID: 159d7c011daa
Revises: c320b5588087
Create Date: 2021-09-22 00:32:19.808568

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "159d7c011daa"
down_revision = "c320b5588087"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raidlog", sa.Column("viewers", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raidlog", "viewers")
    # ### end Alembic commands ###
