"""Add ThisOrThat table

Revision ID: 21372c459cdf
Revises: a149fe1ee31d
Create Date: 2021-10-22 00:30:03.135190

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "21372c459cdf"
down_revision = "a149fe1ee31d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thisorthat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answers", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thisorthat")
    # ### end Alembic commands ###
