"""Add KnownBots table

Revision ID: 3e66938a16ed
Revises: 159d7c011daa
Create Date: 2021-09-26 21:54:39.942452

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3e66938a16ed"
down_revision = "159d7c011daa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knownbots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("botname", sa.String(length=26), nullable=False),
        sa.Column("enableblock", sa.Boolean(), nullable=True),
        sa.Column("added_timestamp", sa.DateTime(), nullable=True),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knownbots")
    # ### end Alembic commands ###
