"""Add KnownBots table

Revision ID: 4376e3882934
Revises: 159d7c011daa
Create Date: 2021-09-26 18:28:56.781887

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4376e3882934"
down_revision = "159d7c011daa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knownbots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("botname", sa.String(length=26), nullable=False),
        sa.Column("autoblock", sa.Boolean(), nullable=True),
        sa.Column("added_timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knownbots")
    # ### end Alembic commands ###
