"""Add Subscriptions table

Revision ID: 513776307301
Revises: 0dacc823f716
Create Date: 2020-12-07 01:09:09.982788

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "513776307301"
down_revision = "0dacc823f716"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.Column("subscription_level", sa.String(length=64), nullable=True),
        sa.Column("cumulative_months", sa.Integer(), nullable=True),
        sa.Column("streak_months", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel"],
            ["users.channel"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "channel"),
    )
    op.create_index(op.f("ix_subscriptions_channel"), "subscriptions", ["channel"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_channel"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
