"""Add added_by column to clips table

Revision ID: 5eeef2a9f4db
Revises: 452c8ad899fb
Create Date: 2021-08-12 22:05:30.082688

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5eeef2a9f4db"
down_revision = "452c8ad899fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clips", sa.Column("added_by", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clips", "added_by")
    # ### end Alembic commands ###
