"""Add ThisOrThat table

Revision ID: 70ac9b1b209d
Revises: a149fe1ee31d
Create Date: 2021-10-25 01:23:39.709390

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "70ac9b1b209d"
down_revision = "a149fe1ee31d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thisorthat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer_1", sa.String(length=256), nullable=False),
        sa.Column("answer_2", sa.String(length=256), nullable=False),
        sa.Column("last_shown", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thisorthat")
    # ### end Alembic commands ###
