"""Add auth levels to webauth

Revision ID: 7e445071ceea
Revises: bddf52d4e7df
Create Date: 2021-07-26 23:47:06.132000

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7e445071ceea"
down_revision = "bddf52d4e7df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("web_auth", sa.Column("admin", sa.Boolean(), nullable=True))
    op.add_column("web_auth", sa.Column("mod", sa.Boolean(), nullable=True))
    op.add_column("web_auth", sa.Column("user", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("web_auth", "user")
    op.drop_column("web_auth", "mod")
    op.drop_column("web_auth", "admin")
    # ### end Alembic commands ###
