"""Add Announcements table

Revision ID: 80d6b49d2d7b
Revises: 513776307301
Create Date: 2020-12-07 01:09:57.486760

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "80d6b49d2d7b"
down_revision = "513776307301"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=1024), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("last_sent", sa.DateTime(), nullable=True),
        sa.Column("times_sent", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("announcements")
    # ### end Alembic commands ###
