"""Add Wigs

Revision ID: 85a4c884a14d
Revises: 336ad6758740
Create Date: 2020-12-26 13:35:24.959829

"""
import sqlalchemy as sa
from alembic import op

from models import Settings


# revision identifiers, used by Alembic.
revision = "85a4c884a14d"
down_revision = "6a59c8ba5242"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wigs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wig_name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wig_name"),
    )

    op.bulk_insert(
        Settings.__table__,
        [
            {
                "key": "WigPollTitle",
                "value": "",
            },
            {
                "key": "WigPollTime",
                "value": 180,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wigs")
    op.execute(f"DELETE FROM `{Settings.__tablename__}` WHERE `key` = 'WigPollTime'")
    op.execute(f"DELETE FROM `{Settings.__tablename__}` WHERE `key` = 'WigPollTitle'")
    # ### end Alembic commands ###
