"""Add IgnoreList table

Revision ID: 8669398e89c8
Revises: c83d861f83b1
Create Date: 2021-02-21 19:02:31.488065

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8669398e89c8"
down_revision = "c83d861f83b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ignorelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ignorelist")
    # ### end Alembic commands ###
