"""Add Trivia table

Revision ID: 8afcb0f7aad7
Revises: 94f1e88e748f
Create Date: 2021-03-22 02:05:14.433645

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8afcb0f7aad7"
down_revision = "94f1e88e748f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trivia_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=1024), nullable=False),
        sa.Column("answers", sa.String(length=2048), nullable=False),
        sa.Column("explain", sa.String(length=1024), nullable=True),
        sa.Column("last_used_date", sa.DateTime(), nullable=True),
        sa.Column("last_update_date", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("reference", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trivia_questions")
    # ### end Alembic commands ###
