"""Add subs_gifted column to Users

Revision ID: 94f1e88e748f
Revises: 8669398e89c8
Create Date: 2021-02-28 18:44:31.070532

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94f1e88e748f"
down_revision = "8669398e89c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("subs_gifted", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET subs_gifted = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subs_gifted")
    # ### end Alembic commands ###
