"""Add webhook settings to Settings table

Revision ID: a149fe1ee31d
Revises: e36c52193286
Create Date: 2021-10-02 02:38:20.670237

"""

import sqlalchemy as sa
from alembic import op

from models import Settings

# revision identifiers, used by Alembic.
revision = "a149fe1ee31d"
down_revision = "e36c52193286"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "knownbots", ["botname"])

    keys = ["to_do_webhook", "link_webhook", "ban_webhook"]
    data = list()

    for key in keys:
        data.append({"key": key, "value": 0})

    for each in data:
        each = [each]
        try:
            op.bulk_insert(Settings.__table__, each)
        except sa.exc.IntegrityError:
            # This is DEFINITELY not the correct way of doing this, but it's going to have to do for now
            print(f"{each[0]} already existed in database")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
