"""Fix column width for commands

Revision ID: b21121e9831b
Revises: 6c0b348d98ac
Create Date: 2021-05-10 02:17:52.361209

"""

# import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b21121e9831b"
down_revision = "6c0b348d98ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE commands MODIFY COLUMN response varchar(520) NOT NULL;")
    op.execute("ALTER TABLE quotes MODIFY COLUMN value varchar(520) NOT NULL;")
    op.execute("ALTER TABLE message_timers MODIFY COLUMN message varchar(520) NOT NULL;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # Nothing to do on downgrade because this originated as a library change, and on a new install will be the
    # above value anyways.
    # ### end Alembic commands ###
