"""Add thisorthat table

Revision ID: b75770a253a2
Revises: a149fe1ee31d
Create Date: 2021-10-25 01:10:59.461038

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b75770a253a2"
down_revision = "a149fe1ee31d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thisorthat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answers", sa.String(length=256), nullable=False),
        sa.Column("last_shown", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thisorthat")
    # ### end Alembic commands ###
