"""Add RaidLog table

Revision ID: c320b5588087
Revises: 0e0348cf8013
Create Date: 2021-09-21 23:58:18.456607

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c320b5588087"
down_revision = "0e0348cf8013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raidlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raider", sa.String(length=26), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raidlog")
    # ### end Alembic commands ###
