"""Add Table for LinksToDiscordIgnoreList

Revision ID: c83d861f83b1
Revises: 85a4c884a14d
Create Date: 2020-12-31 07:30:21.134870

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c83d861f83b1"
down_revision = "85a4c884a14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkstodiscordignorelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkstodiscordignorelist")
    # ### end Alembic commands ###
