"""Add BotRegex table

Revision ID: e36c52193286
Revises: 3e66938a16ed
Create Date: 2021-09-27 01:04:49.471171

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e36c52193286"
down_revision = "3e66938a16ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "botsregex",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("botsregex")
    # ### end Alembic commands ###
