"""Add sound column to TriviaQuestions

Revision ID: e44461c52ba4
Revises: 5eeef2a9f4db
Create Date: 2021-09-04 19:19:50.259010

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e44461c52ba4"
down_revision = "5eeef2a9f4db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trivia_questions", sa.Column("sound", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trivia_questions", "sound")
    # ### end Alembic commands ###
